import Head from 'next/head'
import Image from 'next/image'
import LandingHomeBanner from 'src/layouts/landing/banner'
import LandingHeader from 'src/layouts/landing/header'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div style={{ position: 'relative' }}>
      <Head>
        <title>Sk Project Recycler</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingHeader />
      <LandingHomeBanner id="home" />
      {/* <TimeLine /> */}
    </div>
  )
}
